version: '2.1'

jobs:
    composer:
        docker:
            - image: composer
        steps:
            - checkout
            - restore_cache:
                key: composer-{{ checksum "composer.json" }}
            - run:
                command: |
                    composer global require hirak/prestissimo;
                    composer install --no-interaction --no-progress --classmap-authoritative;
            - save_cache:
                key: composer-{{ checksum "composer.json" }}
                paths:
                    - ./vendor
            - persist_to_workspace:
                root: .
                paths:
                    - vendor

    phpcs:
        docker:
            - image: steevanb/php-code-sniffs:2.0.10
        working_directory: /var/phpcs
        steps:
            - checkout
            - restore_cache:
                keys:
                    - composer-{{ checksum "composer.json" }}
            - run:
                name: phpcs
                command: bin/phpcs

    phpstan:
        docker:
            - image: php:7.3.6-cli-alpine3.10
        steps:
            - checkout
            - restore_cache:
                keys:
                    - composer-{{ checksum "composer.json" }}
            - run:
                name: phpstan
                command: bin/phpstan

    phpunit:
        docker:
            - image: php:7.3.6-cli-alpine3.10
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - composer-{{ checksum "composer.json" }}
            - run:
                  name: phpunit
                  command: bin/phpunit

workflows:
    version: '2.1'
    Code quality:
        jobs:
            - phpcs
            - composer
            - phpstan:
                  requires:
                      - composer
            - phpunit:
                  requires:
                      - composer
